language: ruby
sudo: false
dist: trusty
addons:
  postgresql: "9.5"
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
before_script:
  - bin/rails db:create db:migrate
matrix:
  allow_failures:
    - rvm: ruby-head
